"""
Generate ASCII folder structure map for the project.
Excludes common development artifacts and focuses on source files.
"""

import os
import sys
import io
from pathlib import Path
from datetime import datetime

# Configure UTF-8 output for emoji support (Windows compatibility)
if sys.platform == 'win32' and hasattr(sys.stdout, 'buffer'):
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

# Directories to exclude from the tree
EXCLUDE_DIRS = {
    '__pycache__',
    '.git',
    '.vscode',
    '.idea',
    'venv',
    '.venv',
    'env',
    'node_modules',
    'dist',
    'build',
    'eggs',
    '.eggs',
    'lib',
    'lib64',
    'parts',
    'sdist',
    'var',
    'wheels',
    '.mypy_cache',
    '.pytest_cache',
    '.tox',
    'htmlcov',
    '.claude',
    'logs'
}

# File extensions to exclude
EXCLUDE_EXTENSIONS = {
    '.pyc',
    '.pyo',
    '.pyd',
    '.so',
    '.dll',
    '.dylib',
    '.log',
    '.pid',
    '.egg-info',
    '.coverage',
    '.cache',
    '.obj',
    '.o',
    '.exe'
}

# Files to exclude
EXCLUDE_FILES = {
    '.DS_Store',
    'Thumbs.db',
    'desktop.ini',
    '.gitignore'
}

def should_include(path: Path) -> bool:
    """Check if a path should be included in the tree."""
    if path.is_dir() and path.name in EXCLUDE_DIRS:
        return False
    if path.is_file() and path.suffix in EXCLUDE_EXTENSIONS:
        return False
    if path.is_file() and path.name in EXCLUDE_FILES:
        return False
    return True

def generate_tree(directory: Path, prefix: str = "", is_last: bool = True, max_depth: int = 10, current_depth: int = 0) -> list:
    """Generate ASCII tree structure recursively."""
    if current_depth >= max_depth:
        return []

    lines = []

    try:
        items = sorted([p for p in directory.iterdir() if should_include(p)],
                      key=lambda x: (not x.is_dir(), x.name.lower()))

        for i, item in enumerate(items):
            is_last_item = i == len(items) - 1

            if is_last_item:
                connector = "└── "
                extension = "    "
            else:
                connector = "├── "
                extension = "│   "

            if item.is_dir():
                name = f"📁 {item.name}/"
            else:
                name = item.name

            lines.append(f"{prefix}{connector}{name}")

            if item.is_dir():
                lines.extend(generate_tree(item, prefix + extension, is_last_item, max_depth, current_depth + 1))

    except PermissionError:
        pass

    return lines

def count_files_and_dirs(directory: Path) -> tuple:
    """Count files and directories recursively."""
    file_count = 0
    dir_count = 0

    try:
        for item in directory.rglob('*'):
            if not should_include(item):
                continue
            if item.is_file():
                file_count += 1
            elif item.is_dir():
                dir_count += 1
    except PermissionError:
        pass

    return file_count, dir_count

def main():
    # Get project root (two levels up from this script)
    script_path = Path(__file__).resolve()
    project_root = script_path.parent.parent.parent
    output_dir = script_path.parent.parent / '_claude_outputs'

    # Get project name from folder
    project_name = project_root.name

    # Generate the tree
    print(f"Scanning {project_root}...")
    tree_lines = [f"📁 {project_name}/"]
    tree_lines.extend(generate_tree(project_root, prefix="", max_depth=10))

    # Count files and directories
    file_count, dir_count = count_files_and_dirs(project_root)

    # Generate timestamp
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # Create output content
    output = []
    output.append(f"# {project_name} Folder Structure")
    output.append("")
    output.append(f"**Generated**: {timestamp}")
    output.append(f"**Total Directories**: {dir_count}")
    output.append(f"**Total Files**: {file_count}")
    output.append("")
    output.append("```")
    output.extend(tree_lines)
    output.append("```")
    output.append("")
    output.append("---")
    output.append("")
    output.append("## Notes")
    output.append("- Excludes: Development artifacts (__pycache__, .venv, logs, etc.)")
    output.append("- Excludes: Version control (.git)")
    output.append("- Excludes: IDE files (.vscode, .idea)")
    output.append("- Generated by: `_claude_notes/claude_tools/generate_folder_map.py`")

    # Save to output file
    output_file = output_dir / 'folder_structure.md'
    output_file.parent.mkdir(parents=True, exist_ok=True)

    with open(output_file, 'w', encoding='utf-8') as f:
        f.write('\n'.join(output))

    print(f"\nFolder map generated: {output_file}")
    print(f"Directories: {dir_count}, Files: {file_count}")

    # Also print to console for immediate viewing
    print("\n" + "\n".join(output))

if __name__ == "__main__":
    main()
